mysql:
  image: mysql
  volumes:
     - "./mysql/data:/var/lib/mysql"
     - "./mysql/init:/docker-entrypoint-initdb.d"
  ports:
    - "3306:3306"
  environment:
     MYSQL_ROOT_PASSWORD: password
  command: --innodb-use-native-aio=0

jupyterlab:
  build: '.'
  links:
    - mysql:db
  user: root
  ports:
    - "8888:8888"
  volumes:
    - "./work:/home/jovyan/work"
  environment:
    NB_UID: 500
    GRANT_SUDO: "yes"
  command: start.sh jupyter lab --NotebookApp.password='sha1:f5aea39e2722:39eec01f858d2db72255617fa92664b775eb3ac3'
